# This is a generated file. Not intended for manual editing.
services:
  textnumberconverterapi:
    build:
      context: "/Users/cansozbir/Development/RiderProjects/TextNumberConverterAPI"
      dockerfile: "TextNumberConverterAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/TextNumberConverterAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
    image: "textnumberconverterapi:dev"
    ports: []
    volumes:
    - "/Users/cansozbir/.aspnet/https:/root/.aspnet/https"
    - "/Users/cansozbir/.microsoft/usersecrets:/root/.microsoft/usersecrets"
    - "/Users/cansozbir/Development/RiderProjects/TextNumberConverterAPI/TextNumberConverterAPI:/app:rw"
    working_dir: "/app"
